In [1]:
import pandas as pd

print("Python is working")

Python is working

In [2]:
import pandas as pd
import zipfile

sales_path = "../data/raw/wcer.zip"
products_path = "../data/raw/upccer.csv"

with zipfile.ZipFile(sales_path) as z:
    with z.open("wcer.csv") as f:
        sales = pd.read_csv(f)

products = pd.read_csv(products_path, encoding="latin1")

In [3]:
print(sales.shape)
sales.head()

(6602582, 11)

,STORE,UPC,WEEK,MOVE,QTY,PRICE,SALE,PROFIT,OK,PRICE_HEX,PROFIT_HEX
0,51,317,372,1,1,26.02,NaN,62.52,1,403A051EB851EB85,404F428F5C28F5C3
1,51,317,373,0,1,0.00,NaN,0.00,1,0000000000000000,0000000000000000
2,51,317,374,0,1,0.00,NaN,0.00,1,0000000000000000,0000000000000000
3,51,317,375,0,1,0.00,NaN,0.00,1,0000000000000000,0000000000000000
4,51,317,376,0,1,0.00,NaN,0.00,1,0000000000000000,0000000000000000

In [4]:
print(products.shape)
products.head()

(490, 6)

   COM_CODE         UPC               DESCRIP    SIZE  CASE    NITEM
0       311         317  $TONY THE TIGER T-SH    ASST     1  9900090
1       311  1313000002    NAB SHREDDED WHEAT   10 OZ    12  2513101
2       311  1313000005  NABISCO SHREDDED WHE   15 OZ    12  2513120
3       311  1313000032     NABISCO 100% BRAN   17 OZ    12  2513951
4       311  1313000050  NAB SPOON SIZE SHRED  23.45O    12  2516761

In [5]:
print(sales.shape)
print(sales.columns.tolist())

print(products.shape)
print(products.columns.tolist())

(6602582, 11)
['STORE', 'UPC', 'WEEK', 'MOVE', 'QTY', 'PRICE', 'SALE', 'PROFIT', 'OK', 'PRICE_HEX', 'PROFIT_HEX']
(490, 6)
['COM_CODE', 'UPC', 'DESCRIP', 'SIZE', 'CASE', 'NITEM']

In [6]:
sales.head()

,STORE,UPC,WEEK,MOVE,QTY,PRICE,SALE,PROFIT,OK,PRICE_HEX,PROFIT_HEX
0,51,317,372,1,1,26.02,NaN,62.52,1,403A051EB851EB85,404F428F5C28F5C3
1,51,317,373,0,1,0.00,NaN,0.00,1,0000000000000000,0000000000000000
2,51,317,374,0,1,0.00,NaN,0.00,1,0000000000000000,0000000000000000
3,51,317,375,0,1,0.00,NaN,0.00,1,0000000000000000,0000000000000000
4,51,317,376,0,1,0.00,NaN,0.00,1,0000000000000000,0000000000000000

In [7]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6602582 entries, 0 to 6602581
Data columns (total 11 columns):
 #   Column      Dtype
---  ------      -----
 0   STORE       int64
 1   UPC         int64
 2   WEEK        int64
 3   MOVE        int64
 4   QTY         int64
 5   PRICE       float64
 6   SALE        object
 7   PROFIT      float64
 8   OK          int64
 9   PRICE_HEX   object
 10  PROFIT_HEX  object
dtypes: float64(2), int64(6), object(3)
memory usage: 554.1+ MB

In [8]:
sales.isna().sum()

STORE               0
UPC                 0
WEEK                0
MOVE                0
QTY                 0
PRICE               0
SALE          6242568
PROFIT              0
OK                  0
PRICE_HEX           0
PROFIT_HEX          0
dtype: int64

In [9]:
sales[["MOVE", "QTY", "PRICE", "PROFIT", "OK"]].describe()

               MOVE           QTY         PRICE        PROFIT            OK
count  6.602582e+06  6.602582e+06  6.602582e+06  6.602582e+06  6.602582e+06
mean   1.408119e+01  1.001201e+00  2.241151e+00  1.252218e+01  9.786016e-01
std    5.058522e+01  4.929841e-02  1.541937e+00  1.143999e+01  1.447085e-01
min    0.000000e+00  1.000000e+00  0.000000e+00 -9.969000e+01  0.000000e+00
25%    0.000000e+00  1.000000e+00  0.000000e+00  0.000000e+00  1.000000e+00
50%    8.000000e+00  1.000000e+00  2.790000e+00  1.374000e+01  1.000000e+00
75%    1.700000e+01  1.000000e+00  3.390000e+00  1.861000e+01  1.000000e+00
max    1.868800e+04  4.000000e+00  2.602000e+01  9.999000e+01  1.000000e+00

In [10]:
print(sales["SALE"].value_counts(dropna=False))
print()
print(sales["OK"].value_counts(dropna=False))

SALE
NaN    6242568
B       254261
S        91259
G        11075
C         3418
L            1
Name: count, dtype: int64

OK
1    6461297
0     141285
Name: count, dtype: int64

In [11]:
sales = sales.drop(columns=["PRICE_HEX", "PROFIT_HEX"])

sales.head()

   STORE  UPC  WEEK  MOVE  QTY  PRICE SALE  PROFIT  OK
0     51  317   372     1    1  26.02  NaN   62.52   1
1     51  317   373     0    1   0.00  NaN    0.00   1
2     51  317   374     0    1   0.00  NaN    0.00   1
3     51  317   375     0    1   0.00  NaN    0.00   1
4     51  317   376     0    1   0.00  NaN    0.00   1

In [12]:
sales = sales.merge(
    products[["UPC", "DESCRIP", "SIZE"]],
    on="UPC",
    how="left"
)

sales.head()

,STORE,UPC,WEEK,MOVE,QTY,PRICE,SALE,PROFIT,OK,DESCRIP,SIZE
0,51,317,372,1,1,26.02,NaN,62.52,1,$TONY THE TIGER T-SH,ASST
1,51,317,373,0,1,0.00,NaN,0.00,1,$TONY THE TIGER T-SH,ASST
2,51,317,374,0,1,0.00,NaN,0.00,1,$TONY THE TIGER T-SH,ASST
3,51,317,375,0,1,0.00,NaN,0.00,1,$TONY THE TIGER T-SH,ASST
4,51,317,376,0,1,0.00,NaN,0.00,1,$TONY THE TIGER T-SH,ASST

In [13]:
print("Missing descriptions:", sales["DESCRIP"].isna().sum())

Missing descriptions: 0

In [14]:
sales["UNIT_PRICE"] = sales["PRICE"] / sales["QTY"]

In [15]:
sales["QTY"].value_counts().sort_index()

QTY
1    6597548
2       3300
3        570
4       1164
Name: count, dtype: int64

In [16]:
sales.loc[
    sales["QTY"] > 1,
    ["DESCRIP", "MOVE", "QTY", "PRICE", "UNIT_PRICE"]
].head(20)

                     DESCRIP  MOVE  QTY  PRICE  UNIT_PRICE
466302  BIG G BREAKFAST PACK     1    2    5.0         2.5
466303  BIG G BREAKFAST PACK    12    2    5.0         2.5
466304  BIG G BREAKFAST PACK     8    2    5.0         2.5
466305  BIG G BREAKFAST PACK    21    2    5.0         2.5
466306  BIG G BREAKFAST PACK    28    2    5.0         2.5
466498  BIG G BREAKFAST PACK     5    2    5.0         2.5
466499  BIG G BREAKFAST PACK    11    2    5.0         2.5
466500  BIG G BREAKFAST PACK    12    2    5.0         2.5
466501  BIG G BREAKFAST PACK    24    2    5.0         2.5
466502  BIG G BREAKFAST PACK    24    2    5.0         2.5
466620  BIG G BREAKFAST PACK    13    2    5.0         2.5
466621  BIG G BREAKFAST PACK    13    2    5.0         2.5
466622  BIG G BREAKFAST PACK    12    2    5.0         2.5
466623  BIG G BREAKFAST PACK     4    2    5.0         2.5
466624  BIG G BREAKFAST PACK     8    2    5.0         2.5
466810  BIG G BREAKFAST PACK    10    2    5.0         2.5
466811  BIG G BREAKFAST PACK    13    2    5.0         2.5
466812  BIG G BREAKFAST PACK     8    2    5.0         2.5
466813  BIG G BREAKFAST PACK    14    2    5.0         2.5
466814  BIG G BREAKFAST PACK    16    2    5.0         2.5

In [17]:
sales["REVENUE"] = sales["MOVE"] * sales["UNIT_PRICE"]

In [18]:
sales[
    ["DESCRIP", "MOVE", "QTY", "PRICE", "UNIT_PRICE", "REVENUE"]
].head(10)

                DESCRIP  MOVE  QTY  PRICE  UNIT_PRICE  REVENUE
0  $TONY THE TIGER T-SH     1    1  26.02       26.02    26.02
1  $TONY THE TIGER T-SH     0    1   0.00        0.00     0.00
2  $TONY THE TIGER T-SH     0    1   0.00        0.00     0.00
3  $TONY THE TIGER T-SH     0    1   0.00        0.00     0.00
4  $TONY THE TIGER T-SH     0    1   0.00        0.00     0.00
5  $TONY THE TIGER T-SH     0    1   0.00        0.00     0.00
6  $TONY THE TIGER T-SH     0    1   0.00        0.00     0.00
7  $TONY THE TIGER T-SH     0    1   0.00        0.00     0.00
8  $TONY THE TIGER T-SH     0    1   0.00        0.00     0.00
9  $TONY THE TIGER T-SH     0    1   0.00        0.00     0.00

In [19]:
print("Shape:", sales.shape)
print("Missing descriptions:", sales["DESCRIP"].isna().sum())

print()
print(sales["QTY"].value_counts().sort_index())

print()
print(
    sales.loc[
        sales["QTY"] > 1,
        ["DESCRIP", "MOVE", "QTY", "PRICE", "UNIT_PRICE"]
    ].head(20)
)

Shape: (6602582, 13)
Missing descriptions: 0

QTY
1    6597548
2       3300
3        570
4       1164
Name: count, dtype: int64

                     DESCRIP  MOVE  QTY  PRICE  UNIT_PRICE
466302  BIG G BREAKFAST PACK     1    2    5.0         2.5
466303  BIG G BREAKFAST PACK    12    2    5.0         2.5
466304  BIG G BREAKFAST PACK     8    2    5.0         2.5
466305  BIG G BREAKFAST PACK    21    2    5.0         2.5
466306  BIG G BREAKFAST PACK    28    2    5.0         2.5
466498  BIG G BREAKFAST PACK     5    2    5.0         2.5
466499  BIG G BREAKFAST PACK    11    2    5.0         2.5
466500  BIG G BREAKFAST PACK    12    2    5.0         2.5
466501  BIG G BREAKFAST PACK    24    2    5.0         2.5
466502  BIG G BREAKFAST PACK    24    2    5.0         2.5
466620  BIG G BREAKFAST PACK    13    2    5.0         2.5
466621  BIG G BREAKFAST PACK    13    2    5.0         2.5
466622  BIG G BREAKFAST PACK    12    2    5.0         2.5
466623  BIG G BREAKFAST PACK     4    2    5.0         2.5
466624  BIG G BREAKFAST PACK     8    2    5.0         2.5
466810  BIG G BREAKFAST PACK    10    2    5.0         2.5
466811  BIG G BREAKFAST PACK    13    2    5.0         2.5
466812  BIG G BREAKFAST PACK     8    2    5.0         2.5
466813  BIG G BREAKFAST PACK    14    2    5.0         2.5
466814  BIG G BREAKFAST PACK    16    2    5.0         2.5

In [20]:
zero_sales = sales[sales["MOVE"] == 0]

print("Zero-sales observations:", len(zero_sales))
print("Percent of dataset:", len(zero_sales) / len(sales) * 100)

print()
print("Prices when MOVE = 0:")
print(zero_sales["PRICE"].describe())

Zero-sales observations: 1850703
Percent of dataset: 28.02998887404958

Prices when MOVE = 0:
count    1850703.0
mean           0.0
std            0.0
min            0.0
25%            0.0
50%            0.0
75%            0.0
max            0.0
Name: PRICE, dtype: float64

In [21]:
pd.crosstab(
    sales["MOVE"] == 0,
    sales["PRICE"] == 0,
    margins=True
)

PRICE    False     True      All
MOVE
False  4751202      677  4751879
True         0  1850703  1850703
All    4751202  1851380  6602582

In [22]:
top_upc = (
    sales.groupby(["UPC", "DESCRIP"])["MOVE"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_upc

UPC         DESCRIP
1600066610  CHEERIOS                2061015
3800000120  KELLOGGS CORN FLAKES    1861538
1600066510  CHEERIOS                1595779
1600066590  HONEY NUT CHEERIOS      1555570
3800001520  KELLOGG'S FROSTED FL    1351325
3800001510  KELLOGG'S FROSTED FL    1316328
3800001720  KELLOGGS FRUIT LOOPS    1229989
3800000110  KELLOGGS CORN FLAKES    1209387
3800001611  KELLOGGS SPECIAL K      1109539
3800000520  KELLOGGS RICE KRISPI    1095057
Name: MOVE, dtype: int64

In [24]:
example_upc = 3800000110

sales.loc[
    sales["UPC"] == example_upc,
    ["STORE", "WEEK", "MOVE", "PRICE", "UNIT_PRICE", "SALE", "OK"]
].head(50)

         STORE  WEEK  MOVE  PRICE  UNIT_PRICE SALE  OK
3189042      2     1    41   1.62        1.62  NaN   1
3189043      2     2    64   1.62        1.62  NaN   1
3189044      2     3    54   1.62        1.62  NaN   1
3189045      2     4   213   1.39        1.39    S   1
3189046      2     5    51   1.62        1.62  NaN   1
3189047      2     6    47   1.62        1.62  NaN   1
3189048      2     7    37   1.62        1.62  NaN   1
3189049      2     8    46   1.62        1.62  NaN   1
3189050      2     9    46   1.62        1.62  NaN   1
3189051      2    10    57   1.62        1.62  NaN   1
3189052      2    11    54   1.62        1.62  NaN   1
3189053      2    12    52   1.62        1.62  NaN   1
3189054      2    13    53   1.62        1.62  NaN   1
3189055      2    14    49   1.62        1.62  NaN   1
3189056      2    15    40   1.62        1.62  NaN   1
3189057      2    16    43   1.62        1.62  NaN   1
3189058      2    17    62   1.62        1.62  NaN   1
3189059      2    18    56   1.62        1.62  NaN   1
3189060      2    19    52   1.62        1.62  NaN   1
3189061      2    20    62   1.62        1.62  NaN   1
3189062      2    21    41   1.62        1.62  NaN   1
3189063      2    22    46   1.62        1.62  NaN   1
3189064      2    23    63   1.62        1.62  NaN   1
3189065      2    24    51   1.62        1.62  NaN   1
3189066      2    25    26   1.62        1.62  NaN   1
3189067      2    26    43   1.62        1.62  NaN   1
3189068      2    27    47   1.62        1.62  NaN   1
3189069      2    28    50   1.62        1.62  NaN   1
3189070      2    29    45   1.62        1.62  NaN   1
3189071      2    30     4   1.62        1.62  NaN   0
3189072      2    31    57   1.62        1.62  NaN   1
3189073      2    32    46   1.62        1.62  NaN   1
3189074      2    33    47   1.62        1.62  NaN   1
3189075      2    34    59   1.62        1.62  NaN   1
3189076      2    35    59   1.62        1.62  NaN   1
3189077      2    36    49   1.62        1.62  NaN   1
3189078      2    37    33   1.62        1.62  NaN   1
3189079      2    38    46   1.62        1.62  NaN   1
3189080      2    39    40   1.62        1.62  NaN   1
3189081      2    40    34   1.62        1.62  NaN   1
3189082      2    41    35   1.62        1.62  NaN   1
3189083      2    42    46   1.62        1.62  NaN   1
3189084      2    43    39   1.62        1.62  NaN   1
3189085      2    44    46   1.62        1.62  NaN   1
3189086      2    45    39   1.62        1.62  NaN   1
3189087      2    46    36   1.62        1.62  NaN   1
3189088      2    47    23   1.62        1.62  NaN   1
3189089      2    48    34   1.62        1.62  NaN   1
3189090      2    49     4   1.62        1.62  NaN   0
3189091      2    50    45   1.62        1.62  NaN   1

In [25]:
sales.groupby("OK")[["MOVE", "PRICE", "UNIT_PRICE", "PROFIT"]].describe()

         MOVE                                                           PRICE  \
        count       mean         std  min  25%  50%   75%      max      count
OK
0    141285.0  15.608437  228.921912  0.0  0.0  0.0   4.0  18688.0   141285.0
1   6461297.0  14.047790   38.325733  0.0  0.0  8.0  17.0  17824.0  6461297.0

              ... UNIT_PRICE            PROFIT                               \
        mean  ...        75%    max      count       mean        std    min
OK            ...
0   0.859911  ...       2.29   6.98   141285.0   4.773447   8.246307   0.00
1   2.271354  ...       3.39  26.02  6461297.0  12.691618  11.441437 -99.69


    25%    50%    75%    max
OK
0   0.0   0.00   9.77  99.99
1   0.0  13.98  18.73  99.99

[2 rows x 32 columns]

In [26]:
sales.groupby("OK").agg(
    observations=("UPC", "size"),
    avg_units=("MOVE", "mean"),
    avg_price=("UNIT_PRICE", "mean"),
    max_price=("UNIT_PRICE", "max"),
    avg_profit=("PROFIT", "mean")
)

    observations  avg_units  avg_price  max_price  avg_profit
OK
0         141285  15.608437   0.858936       6.98    4.773447
1        6461297  14.047790   2.270148      26.02   12.691618

In [27]:
analysis = sales[
    (sales["MOVE"] > 0) &
    (sales["UNIT_PRICE"] > 0) &
    (sales["OK"] == 1)
].copy()

print("Raw observations:", len(sales))
print("Analysis observations:", len(analysis))
print("Percent retained:", len(analysis) / len(sales) * 100)

Raw observations: 6602582
Analysis observations: 4707776
Percent retained: 71.30204516960184

In [28]:
analysis.nlargest(
    20,
    "UNIT_PRICE"
)[
    ["STORE", "UPC", "DESCRIP", "SIZE", "WEEK",
     "MOVE", "QTY", "PRICE", "UNIT_PRICE", "SALE", "OK"]
]

,STORE,UPC,DESCRIP,SIZE,WEEK,MOVE,QTY,PRICE,UNIT_PRICE,SALE,OK
0,51,317,$TONY THE TIGER T-SH,ASST,372,1,1,26.02,26.02,NaN,1
29,74,317,$TONY THE TIGER T-SH,ASST,367,1,1,19.06,19.06,NaN,1
153,111,317,$TONY THE TIGER T-SH,ASST,381,1,1,10.46,10.46,NaN,1
4482875,100,3800004900,BITE SIZE FRSTD MINI,19 OZ,339,825,1,9.71,9.71,S,1
5258427,5,3800054280,KELLOGS FRSTED FLKS,50 OZ,212,3,1,7.49,7.49,NaN,1
5258428,5,3800054280,KELLOGS FRSTED FLKS,50 OZ,213,3,1,7.49,7.49,NaN,1
5258430,5,3800054280,KELLOGS FRSTED FLKS,50 OZ,215,5,1,7.49,7.49,NaN,1
5258431,5,3800054280,KELLOGS FRSTED FLKS,50 OZ,216,5,1,7.49,7.49,NaN,1
5258432,5,3800054280,KELLOGS FRSTED FLKS,50 OZ,217,7,1,7.49,7.49,NaN,1
5258433,5,3800054280,KELLOGS FRSTED FLKS,50 OZ,218,3,1,7.49,7.49,NaN,1
5258435,5,3800054280,KELLOGS FRSTED FLKS,50 OZ,220,5,1,7.49,7.49,NaN,1
5258969,21,3800054280,KELLOGS FRSTED FLKS,50 OZ,198,7,1,7.49,7.49,NaN,1
5258970,21,3800054280,KELLOGS FRSTED FLKS,50 OZ,199,8,1,7.49,7.49,NaN,1
5258971,21,3800054280,KELLOGS FRSTED FLKS,50 OZ,200,3,1,7.49,7.49,NaN,1
5258972,21,3800054280,KELLOGS FRSTED FLKS,50 OZ,201,4,1,7.49,7.49,NaN,1
5258973,21,3800054280,KELLOGS FRSTED FLKS,50 OZ,202,3,1,7.49,7.49,NaN,1
5258974,21,3800054280,KELLOGS FRSTED FLKS,50 OZ,203,4,1,7.49,7.49,NaN,1
5258975,21,3800054280,KELLOGS FRSTED FLKS,50 OZ,204,5,1,7.49,7.49,NaN,1
5258976,21,3800054280,KELLOGS FRSTED FLKS,50 OZ,205,5,1,7.49,7.49,NaN,1
5258977,21,3800054280,KELLOGS FRSTED FLKS,50 OZ,206,6,1,7.49,7.49,NaN,1

In [29]:
analysis.nlargest(
    20,
    "MOVE"
)[
    ["STORE", "UPC", "DESCRIP", "SIZE", "WEEK",
     "MOVE", "UNIT_PRICE", "SALE", "OK"]
]

,STORE,UPC,DESCRIP,SIZE,WEEK,MOVE,UNIT_PRICE,SALE,OK
2856676,86,3000006560,CAPN CRUNCH JUMBO CR,15 OZ,395,17824,1.50,NaN,1
894129,86,1600066110,WHEATIES,12 OZ,376,10774,0.99,NaN,1
5219902,86,3800016820,KLLG HNY CRUNCH CORN,15.1 O,376,10498,1.99,S,1
6582256,86,79166918102,RALSTON RICE CHEX,12 OZ,375,9785,1.69,S,1
2856654,86,3000006560,CAPN CRUNCH JUMBO CR,15 OZ,373,9622,1.59,S,1
2907184,86,3000006610,CAPN CRUNCH CEREAL,16 OZ,373,9440,1.59,S,1
6598943,86,79166919541,RALSTON CORN CHEX,12 OZ,375,8849,1.69,S,1
2907206,86,3000006610,CAPN CRUNCH CEREAL,16 OZ,395,8406,1.50,NaN,1
1075329,86,1600066610,CHEERIOS,15 OZ,365,6126,1.67,B,1
5222452,86,3800016830,KLLG HNY CRUNCH CORN,21.3 O,368,5570,1.99,B,1
3918748,86,3800001710,KELLOGG FROOT LOOPS,11 OZ,339,5470,2.00,S,1
3883269,86,3800001621,KELLOGGS SPECIAL K,18 OZ,366,5217,2.27,S,1
2856625,86,3000006560,CAPN CRUNCH JUMBO CR,15 OZ,342,5213,1.84,S,1
1075307,86,1600066610,CHEERIOS,15 OZ,343,5184,1.99,S,1
3632335,86,3800001111,KELLOGGS COCOA KRISP,15 OZ,391,5079,1.99,S,1
2907155,86,3000006610,CAPN CRUNCH CEREAL,16 OZ,342,5012,1.84,S,1
2825441,86,3000006500,QUAKER P.B. CAPTAIN,15 OZ,342,4787,1.84,S,1
709234,86,1600065850,WHOLE GRAIN TOTAL,12 OZ,356,4732,1.66,S,1
3265243,73,3800000127,KELLOGGS CORN FLAKE,24 OZ,56,4336,0.99,NaN,1
3493046,86,3800000820,KELLOGG'S RAISIN BRA,20 OZ,333,4165,2.50,S,1

In [30]:
analysis["UNIT_PRICE"].quantile(
    [0, .001, .01, .05, .25, .50, .75, .95, .99, .999, 1]
)

0.000     0.05
0.001     0.39
0.010     0.79
0.050     1.88
0.250     2.65
0.500     3.15
0.750     3.59
0.950     4.37
0.990     4.85
0.999     5.59
1.000    26.02
Name: UNIT_PRICE, dtype: float64

In [31]:
analysis["MOVE"].quantile(
    [0, .001, .01, .05, .25, .50, .75, .95, .99, .999, 1]
)

0.000        1.0
0.001        1.0
0.010        1.0
0.050        2.0
0.250        7.0
0.500       13.0
0.750       21.0
0.950       46.0
0.990      134.0
0.999      553.0
1.000    17824.0
Name: MOVE, dtype: float64

In [32]:
sales[sales["UPC"] == 317][
    ["UPC", "DESCRIP", "SIZE"]
].drop_duplicates()

   UPC               DESCRIP  SIZE
0  317  $TONY THE TIGER T-SH  ASST

In [33]:
analysis = analysis[analysis["UPC"] != 317].copy()

In [34]:
analysis.groupby("STORE").agg(
    total_units=("MOVE", "sum"),
    observations=("MOVE", "size"),
    avg_units=("MOVE", "mean"),
    median_units=("MOVE", "median"),
    max_units=("MOVE", "max")
).sort_values("avg_units", ascending=False).head(15)

       total_units  observations  avg_units  median_units  max_units
STORE
137        1761941         49886  35.319348          27.0       1088
102        1720799         59269  29.033711          19.0       3015
109        1677248         58886  28.482967          22.0       1658
122        1665862         59008  28.231121          21.0       1902
80         1637401         58382  28.046333          20.0       1639
126        1705198         62078  27.468636          19.0       1835
143         184609          7084  26.059994          19.0       1040
128        1460957         56505  25.855358          18.0       2660
135         193843          7575  25.589835          16.0       1477
70         1438968         56742  25.359839          17.0       1927
44         1432375         56518  25.343696          19.0       1316
139         856128         33987  25.189867          17.0       2530
8          1437135         57781  24.872103          16.0       3153
73         1409985         56909  24.776134          15.0       4336
132        1504985         61008  24.668650          18.0       2825

In [35]:
analysis.assign(
    store_group=analysis["STORE"].eq(86).map({
        True: "Store 86",
        False: "Other stores"
    })
).groupby("store_group")["MOVE"].describe()

                  count       mean         std  min  25%   50%   75%      max
store_group
Other stores  4650108.0  19.223630   39.457046  1.0  7.0  13.0  21.0   4336.0
Store 86        57663.0  23.845083  175.452498  1.0  8.0  13.0  19.0  17824.0

In [36]:
analysis.loc[
    analysis["STORE"] == 86,
    ["WEEK", "MOVE"]
].groupby("WEEK").sum().sort_values(
    "MOVE",
    ascending=False
).head(20)

       MOVE
WEEK
395   33757
376   24436
343   24198
373   22852
375   21670
342   18557
339   18249
344   14241
398   13987
341   12941
340   12918
332   12561
391   12061
356   11943
336   11325
366   11232
338   11200
346   11077
323   11009
331   10654

In [37]:
analysis.nsmallest(
    30,
    "UNIT_PRICE"
)[
    ["STORE", "UPC", "DESCRIP", "SIZE", "WEEK",
     "MOVE", "QTY", "PRICE", "UNIT_PRICE", "SALE", "PROFIT"]
]

,STORE,UPC,DESCRIP,SIZE,WEEK,MOVE,QTY,PRICE,UNIT_PRICE,SALE,PROFIT
5671820,136,3828198105,DOM TRIAL SIZE CEREA,144 CT,139,81,1,0.05,0.05,NaN,55.36
5671907,137,3828198105,DOM TRIAL SIZE CEREA,144 CT,134,1,1,0.05,0.05,NaN,55.36
5664165,136,3828198101,DOM TRIAL SIZE CEREA,144 CT,139,66,1,0.06,0.06,NaN,16.66
3976661,98,3800001727,KELLOGGS FRUIT LOOPS,19.7 O,369,1025,1,0.09,0.09,NaN,-32.10
2541351,18,3000004350,CAP'N CRUNCH CHRISTM,15 OZ,330,1,1,0.10,0.10,B,-5.00
4158228,98,3800002970,KELLOGGS APPLE JACKS,19.1,369,511,1,0.10,0.10,NaN,-20.28
5657268,21,3828198101,DOM TRIAL SIZE CEREA,144 CT,139,14,1,0.10,0.10,NaN,50.00
5663670,129,3828198101,DOM TRIAL SIZE CEREA,144 CT,137,20,1,0.10,0.10,NaN,50.00
5668914,98,3828198105,DOM TRIAL SIZE CEREA,144 CT,154,2,1,0.10,0.10,NaN,50.00
5671331,129,3828198105,DOM TRIAL SIZE CEREA,144 CT,137,33,1,0.10,0.10,NaN,50.00
6543056,137,7572514080,~GENERIC QUICK OATS,42 OZ,214,1,1,0.10,0.10,NaN,-54.00
5663669,129,3828198101,DOM TRIAL SIZE CEREA,144 CT,136,72,1,0.13,0.13,NaN,92.30
5664949,21,3828198105,DOM TRIAL SIZE CEREA,144 CT,139,29,1,0.13,0.13,NaN,92.30
5661205,98,3828198101,DOM TRIAL SIZE CEREA,144 CT,154,6,1,0.14,0.14,NaN,78.57
5661454,102,3828198101,DOM TRIAL SIZE CEREA,144 CT,129,66,1,0.15,0.15,NaN,66.66
5669163,102,3828198105,DOM TRIAL SIZE CEREA,144 CT,129,164,1,0.15,0.15,NaN,66.66
5671330,129,3828198105,DOM TRIAL SIZE CEREA,144 CT,136,58,1,0.15,0.15,NaN,66.66
5657704,44,3828198101,DOM TRIAL SIZE CEREA,144 CT,143,51,1,0.16,0.16,NaN,56.25
5665387,44,3828198105,DOM TRIAL SIZE CEREA,144 CT,143,54,1,0.16,0.16,NaN,56.25
1829358,131,1780000072,DOUBLE CHEX PP .39Õ,1 OZ,149,24,1,0.20,0.20,NaN,2.50
5669000,100,3828198105,DOM TRIAL SIZE CEREA,144 CT,140,70,1,0.20,0.20,NaN,25.00
5661291,100,3828198101,DOM TRIAL SIZE CEREA,144 CT,140,50,1,0.21,0.21,NaN,19.04
309783,137,1600062640,G.M. BERRY BERRY KIX,18 OZ,215,2,1,0.25,0.25,NaN,-40.00
1340002,9,1600067720,BIG G TRAIL SIZE PAL,1.0,392,38,1,0.25,0.25,NaN,-79.60
1404334,9,1600068100,BIG G TRAIL SIZE PAL,1.0,392,4,1,0.25,0.25,NaN,-79.60
2032394,75,1780014313,URKEL-O'S CEREAL,11 OZ,157,44,1,0.25,0.25,NaN,61.44
5019371,98,3800013544,KELLOGG DOUBLE DIP S,1 OZ,132,92,1,0.25,0.25,NaN,30.40
5019372,98,3800013544,KELLOGG DOUBLE DIP S,1 OZ,133,2,1,0.25,0.25,NaN,30.40
5022846,131,3800013544,KELLOGG DOUBLE DIP S,1 OZ,136,2,1,0.25,0.25,NaN,30.40
5537149,2,3828125053,DOMINICK'S T-SIZE SH,ASST,46,12,4,1.00,0.25,NaN,36.40

In [38]:
duplicates = analysis.duplicated(
    subset=["STORE", "UPC", "WEEK"],
    keep=False
)

print("Duplicate rows:", duplicates.sum())

Duplicate rows: 0

In [39]:
products[["UPC", "DESCRIP", "SIZE"]].to_string(index=False)

"        UPC              DESCRIP   SIZE\n        317 $TONY THE TIGER T-SH   ASST\n 1313000002   NAB SHREDDED WHEAT  10 OZ\n 1313000005 NABISCO SHREDDED WHE  15 OZ\n 1313000032    NABISCO 100% BRAN  17 OZ\n 1313000050 NAB SPOON SIZE SHRED 23.45O\n 1313000054 NAB SPOON SIZE SHRED 17.2 O\n 1313000148  NABISCO TEAM FLAKES  13 OZ\n 1313000698 NABISCO CREAM OF RIC  14 OZ\n 1313001041 NABISCO OAT BRAN RAI 15.5 O\n 1313001059 NABISCO WHEAT N BRAN  18 OZ\n 1313001145 NABISCO FRUIT WHEATS 15.5 O\n 1313001146  NAB RASPBERRY FRUIT 15.5 O\n 1313001854  NAB SHRED WHT W/OAT  18 OZ\n 1313002033 NABISCO 100% BRAN W/  17 OZ\n 1313002401 TEDDY GRAHAMS BRKFST  15 OZ\n 1313002402 TEDDY GRAHAMS BRKFST  15 OZ\n 1313002403 TEDDY GRAHAMS BRKFST  15 OZ\n 1313005152 NAB FROST WHEAT SQUA  15 OZ\n 1313005154    NAB FROSTED WHEAT  20 OZ\n 1313018155 ~NABISCO FROSTED WHE  15 OZ\n 1600000000 BERRY KIX/WHT TOTAL/   1 CT\n 1600062360 TRIPLES/KRAFT MARSHM 18.7 O\n 1600062370  $ GEN MILLS TRIPLES 13.3 O\n 1600062380     G. MILLS TRIPLES 18.75O\n 1600062580 G. MILLS BENEFIT W/R  15 OZ\n 1600062600 G. MILLS BENEFIT CER 12.5 O\n 1600062640 G.M. BERRY BERRY KIX  18 OZ\n 1600062680      BERRY BERRY KIX 12.7 O\n 1600062740 BIG G APPLE-CIN CHEE 1.35 O\n 1600062750 APPLE CINNAMON CHERR  15 OZ\n 1600062760 APPLE CINNAMON CHEER  21 OZ\n 1600063100 ~RIPPLE CRISP HONEY-  15 OZ\n 1600063110 ~RIPPLE CRISP-GOLDEN 13.5OZ\n 1600063830  WHEATIES HONEY GOLD 14.75O\n 1600063840  WHEATIES HONEY GOLD 21.25O\n 1600064300     FROSTED CHEERIOS 14.2 O\n 1600064310     FROSTED CHEERIOS 20.2 O\n 1600064360 BIG G BREAKFAST PACK 7.5 OZ\n 1600064380 GENERAL MILLS SUN CR  14 OZ\n 1600064400 GENERAL MILLS SUN CR 14.5 O\n 1600064450 BIG G SPRINKLE SPANG  13 OZ\n 1600064670 GM PEANUT BUTTER PUF  14.25\n 1600064730 ~GM HIDDEN TREASURES 13.75O\n 1600064740 WHEATIES DUNKA-BALLS 13.5OZ\n 1600064760 WHEATIES QUARTERBACK 13.5OZ\n 1600064820              BASIC 4 14.5 O\n 1600064840              BASIC 4 14.8 O\n 1600065110 GM N.V LOWFAT GRANOL  17 OZ\n 1600065120 B.C CINN STREUSEL CE 13.75O\n 1600065130 BC DUTCH APPLE CEREA 16.5OZ\n 1600065190      CHEERIOS BND PK  30 OZ\n 1600065400 SMORES CRUNCH CEREAL  14 OZ\n 1600065420 GENERAL MILLS CLUSTE  13 OZ\n 1600065490  CLUSTERS TRIAL SIZE  1.7OZ\n 1600065600       G.M. FIBER ONE  16 OZ\n 1600065620       G.M. FIBER ONE  16 OZ\n 1600065700 CINNAMON TOAST CRUNC  14 OZ\n 1600065720 CINNAMON TOAST CRUNC 20.3 O\n 1600065727 CINNAMON TOAST CRUNC  14 OZ\n 1600065850    WHOLE GRAIN TOTAL  12 OZ\n 1600065890                TOTAL  18 OZ\n 1600065910 GENERAL MILLS CLUSTE 15.5OZ\n 1600065920 GENERAL MILLS CLUSTE 15.5OZ\n 1600065960    TOTAL CORN FLAKES  10 OZ\n 1600065980      RAISIN NUT BRAN  15 OZ\n 1600065990   GM RAISIN NUT BRAN  20 OZ\n 1600066110             WHEATIES  12 OZ\n 1600066210             WHEATIES  18 OZ\n 1600066310                  KIX   9 OZ\n 1600066370                  KIX  13 OZ\n 1600066510             CHEERIOS  10 OZ\n 1600066590   HONEY NUT CHEERIOS  14 OZ\n 1600066610             CHEERIOS  15 OZ\n 1600066660             CHEERIOS  20 OZ\n 1600066740 CHEERIOS CRAYOLA TRA 8.75 O\n 1600066750   HONEY NUT CHEERIOS  20 OZ\n 1600066820 H.N. CHEERIOS BND PK  28 OZ\n 1600066950   HONEY NUT CHEERIOS  27 OZ\n 1600066960 OATMEAL RAISIN CRISP  2.3OZ\n 1600066970 OATMEAL CRISP W/RAIS  15 OZ\n 1600067030 OATMEAL RAISIN CRISP  20 OZ\n 1600067070 OATMEAL CRISP CEREAL 18.25O\n 1600067110  BIG G OATMEAL CRISP 15.5OZ\n 1600067140 OATMEAL CRISP WITH A  15 OZ\n 1600067350 BIG G TRIAL SIZE PAL  ASSTD\n 1600067400                 TRIX  17 OZ\n 1600067440                 TRIX  12 OZ\n 1600067460 TRIX/CHEERIOS CRAYOL  ASSTD\n 1600067720 BIG G TRAIL SIZE PAL    1.0\n 1600067970       GOLDEN GRAHAMS  18 OZ\n 1600068050       GOLDEN GRAHAMS  12 OZ\n 1600068090    BUNUELITOS CEREAL 12.5OZ\n 1600068100 BIG G TRAIL SIZE PAL    1.0\n 1600068170          COCOA PUFFS  12 OZ\n 1600068260          COCOA PUFFS 13.8 O\n 1600068270 BIG G TRIAL SIZE PAL  ASSTD\n 1600068290   HONEY NUT CHEERIOS  27 OZ\n 1600068310 GM TOTAL RAISIN BRAN 13.5OZ\n 1600068330    TOTAL RAISIN BRAN  20 OZ\n 1600068350    TOTAL RAISIN BRAN  18 OZ\n 1600068360    TOTAL RAISIN BRAN  24 OZ\n 1600068450 CRISPY WHEATS & RAIS  18 OZ\n 1600068500 BIG G TRAIL SIZE PAL    1.0\n 1600068560  FRANKENBERRY CEREAL  12 OZ\n 1600068640 COUNT CHOCULA CEREAL  12 OZ\n 1600068780 MULTI GRAIN CHEERIOS 11.25O\n 1600068790 MULTI GRAIN CHEERIOS  16 OZ\n 1600068870         LUCKY CHARMS  14 OZ\n 1600068879 HOLIDAY LUCKY CHARMS  14 OZ\n 1600068890         LUCKY CHARMS  20 OZ\n 1600068920 GENERAL MILLS KABOOM  10 OZ\n 1600069270   HONEY NUT CHEERIOS  27 OZ\n 1600069320       GOLDEN GRAHAMS  13 OZ\n 1600069750 ~TEAM USA CHERRIOS (  13 OZ\n 1600069820 GEN MLLS FRENCH TOAS 15.75O\n 1600069880  SINGLE VARIETY PACK   6 OZ\n 1600069900 HONEY TOASTED OAT FI   9 OZ\n 1600069910      CINNAMON FINGOS 8.25 O\n 1600081570 GM JURASSIC CRUNCH C 11.25O\n 1600084320     FROSTED CHEERIOS  28 OZ\n 1600085920   HONEY NUT CLUSTERS 17.2 O\n 1600085930 BIG G TRIAL SIZE PAL  ASSTD\n 1600085970     ~RAISIN NUT BRAN 14.5 O\n 1600086980   GM RAISIN NUT BRAN  21 OZ\n 1600087030 GM OATMEAL RAISIN CR 21.5 O\n 1600087110  BIG G OATMEAL CRISP 16.8 O\n 1600087140 GM OATMEAL CRISP W/A   16.4\n 1600087980 OATMEAL CRISP W/RAIS  16 OZ\n 1600094840  GENERAL MILLS BASIC 16.2 O\n 1600097110 GM OATML RSN CRSP AP 17.5 O\n 1600097140 GM OATML RSN CRSP AL 17.5 O\n 1600097980 GM OATML RSN CRSP RA  19.25\n 1780000072  DOUBLE CHEX PP .39Õ   1 OZ\n 1780010207 ~RALSTON BANANA WALN 13.5OZ\n 1780010304  MUESLI APPLE ALMOND 13.5OZ\n 1780010320 MUESLI W/CRANBERRIES   3 OZ\n 1780010359 ~MUESLI W/ CRANBERRI 13.5OZ\n 1780010375 RALSTON MUESLI RAISI 13.5OZ\n 1780010508 RALSTON MORNING FUNN  14 OZ\n 1780010537 ~RASPBERRY ALMOND MU 13.5OZ\n 1780010605 ~MUESLI STRAWBERRY P 13.5OZ\n 1780010618  RALSTON BLBRY PECAN 13.5OZ\n 1780013097 HONEY ALMOND DELIGHT 1.2 OZ\n 1780013136 ALMOND DELIGHT BONUS  18 OZ\n 1780013217 ~HONEY ALMOND DELIGH  15 OZ\n 1780013709  ~RALSTON GRAHAM CHX 15.5OZ\n 1780013741 GRAHAM CHEX 40% BONU 21.7 O\n 1780013806        JETSON CEREAL  14 OZ\n 1780014216  BILL & TED'S CEREAL 12.5OZ\n 1780014313     URKEL-O'S CEREAL  11 OZ\n 1780014407     OAT BRAN OPTIONS  17 OZ\n 1780014478 OAT BRAN OPTIONS SHI 1.45 O\n 1780014601 RALSTON RICE BRAN OP  17 OZ\n 1780014834  RALSTON DOUBLE CHEX 19.25Z\n 1780014973  RALSTON DOUBLE CHEX 19.25Z\n 1780014986  RALSTON DOUBLE CHEX 13.75O\n 1780015011   RALSTON/WHEAT CHEX  16 OZ\n 1780015260   RALSTON/WHEAT CHEX  16 OZ\n 1780015707    HOT WHEELS CEREAL  14 OZ\n 1780016023 GHOST BUSTERS II CER  14 OZ\n 1780016049     RALSTON OAT BRAN  14 OZ\n 1780016201   HONEY NUT OAT CHEX  16 OZ\n 1780016308        BATMAN CEREAL  14 OZ\n 1780016311 BATMAN RETURNS CEREA 12.5OZ\n 1780016502      NINTENDO CEREAL  13 OZ\n 1780016515 PRINCE OF THIEVES CE 11.5 O\n 1780016609  BRKFAST WITH BARBIE  14 OZ\n 1780016900 RALSTON HONEY GRAHAM  14 OZ\n 1780017307 BREAKFAST ON THE RUN 1.25 O\n 1780017909 ADDAMS FAMILY CEREAL  11 OZ\n 1780018270    RALSTON RICE CHEX  12 OZ\n 1780018429 FROSTED RICE CHEX JU 12.5OZ\n 1780018704 TEENAGE MUTANT NINJA 12.5OZ\n 1780018982 COOKIE CRISP CHOCOLA  11 OZ\n 1780019062 MULTI BRAN CHEX BONU 19.2 O\n 1780019091    RALSTON BRAN CHEX  16 OZ\n 1780019266    RALSTON CORN CHEX  12 OZ\n 1780019538 BREAKFAST ON THE RUN 1.25 O\n 1780019541    RALSTON CORN CHEX  12 OZ\n 1780030180 BREAKFAST ON THE RUN 1.25 O\n 1862702345  KASHI PUFFED CEREAL 7.5 OZ\n 1862702346  KASHI MEDLEY CEREAL  14 OZ\n 1862702349   HONEY PUFFED KASHI 11.25O\n 2430003155  SUNBELT BERRY BASIC  12 OZ\n 2430003165 SUNBELT GRANOLA CERE  16 OZ\n 2430003175 SUNBELT MUESLI CEREA  14 OZ\n 2480000119 KRETSCHMER WHEAT GER  12 OZ\n 3000001680  QUAKER RTE OAT BRAN 15.5OZ\n 3000002150 QUAKER HONEY CRNCH R  13 OZ\n 3000002350  KRETCHMER HONEY WHT  10 OZ\n 3000002360 QUAKER OATS PLUS FIB  19 OZ\n 3000002380 QUAKER OATS FIBER RA 12.8 O\n 3000002390    QUAKER MULTIGRAIN  18 OZ\n 3000002550 QUAKER TOASTED OATME  16 OZ\n 3000002580 QUAKER TOASTED OATME  16 OZ\n 3000002720 KRETCHMER TOASTED WH  12 OZ\n 3000002810 QUAKER TINY TOON CER   9 OZ\n 3000004340  CAP'N CRNCH BERRIES  21 OZ\n 3000004350 CAP'N CRUNCH CHRISTM  15 OZ\n 3000006020     ~HOME RUN CRUNCH 18.7 O\n 3000006080 QUAKER LIFE CINNAMON  23 OZ\n 3000006110   QUAKER LIFE CEREAL  23 OZ\n 3000006140 QUAKER  JUMBO CRUNCH  21 OZ\n 3000006150 QUAKER CINAMON OAT S  16 OZ\n 3000006151 QUAKER OAT SQUARES B  32 OZ\n 3000006190   QUAKER PUFFED RICE   7 OZ\n 3000006200 CAPTAIN CRUNCH JUMBO  20 OZ\n 3000006201 CAP'N CRUNCH 50[ OFF  20 OZ\n 3000006230 CAP N CRUNCH DEEP SE  15 OZ\n 3000006300 CAPTAIN CRUNCH JUMBO  22 OZ\n 3000006400 QUAKER JUMBO OAT SQU  26 OZ\n 3000006410  QUAKER PUFFED WHEAT   6 OZ\n 3000006430   QUAKER OAT SQUARES  16 OZ\n 3000006500  QUAKER P.B. CAPTAIN  15 OZ\n 3000006560 CAPN CRUNCH JUMBO CR  15 OZ\n 3000006570 QUAKER JUMBO OAT SQU  26 OZ\n 3000006610   CAPN CRUNCH CEREAL  16 OZ\n 3000006700 QUAKER 100% CEREAL-O  32 OZ\n 3000006720 QUAKER 100% CEREAL H  32 OZ\n 3000006740 QUAKER NATURAL LOWFA 15.5 O\n 3000006750  QUAKER 100% NATURAL  29 OZ\n 3000006760  QUAKER 100% NATURAL  16 OZ\n 3000006780 QUAKER 100% CEREAL H  16 OZ\n 3000006860 QKR CRNCHY CORN BRAN  16 OZ\n 3000006870  QUAKER CRUNCHY BRAN  12 OZ\n 3000006920 QUAKER TRIPLE CRUNCH  18 OZ\n 3000006990     QUAKER RICE BRAN 13.75O\n 3000007800  QUAKER OH'S APL/CIN 12.7 O\n 3000007830  QUAKER OH'S CRUNCHY  12.75\n 3000007840 QUAKER OH'S HONEY GR  12 OZ\n 3000020123 MOTHER'S OAT BRAN HO  16 OZ\n 3000034855   $QUAKER APPLE ZAPS  14 OZ\n 3000034860 $QUAKER SWEET CRUNCH  16 OZ\n 3000034861   QUAKER SWEET PUFFS  18 OZ\n 3000034862  QUAKER COCOA BLASTS  13 OZ\n 3000034863 QKR BAGGED CEREAL-FR  14 OZ\n 3000043316 QUAKER CLUB PACK CAP 2/20 O\n 3000043338 QUAKER LIFE CEREAL T   1 OZ\n 3000043344         LIFE CEREALS   1 OZ\n 3680011885 W.C. X-RAISIN BRAN C  20 OZ\n 3800000000 RICE KRISPIES HOLIDA  15 OZ\n 3800000101 ~KELLOGGS CORN FLAKE   7 OZ\n 3800000110 KELLOGGS CORN FLAKES  12 OZ\n 3800000111 KELLOGG'S CORN FLAKE 11.9OZ\n 3800000120 KELLOGGS CORN FLAKES  18 OZ\n 3800000127  KELLOGGS CORN FLAKE  24 OZ\n 3800000311 ~KELLOGG'S FRSTD RIC  14 OZ\n 3800000401 KELLOGGS NUT & HONEY  16 OZ\n 3800000510 KELLOGGS RICE KRISPI  10 OZ\n 3800000520 KELLOGGS RICE KRISPI  15 OZ\n 3800000535 KELLOGGS RICE KRISPI  19 OZ\n 3800000600 ~KELLOGG BRAN FLAKES 17.3 O\n 3800000611 KELLOGGS BRAN FLAKES  16 OZ\n 3800000640  ~KELL COMPLETE BRAN  12 OZ\n 3800000801 KELLOGGS RAISIN BRAN 10.5OZ\n 3800000810 KELLOGGS RAISIN BRAN  15 OZ\n 3800000820 KELLOGG'S RAISIN BRA  20 OZ\n 3800000828 KELLOGGS RAISIN BRAN 25.5 O\n 3800000900 KELLOGGS APPLE CINNA 16.5OZ\n 3800001003  KELLOGG'S CORN POPS 10.9 O\n 3800001004 KELLOGG CORN POPS P.  13 OZ\n 3800001011   KELLOGGS CORN POPS  15 OZ\n 3800001070  KELLOGG'S CORN POPS 18.8 O\n 3800001111 KELLOGGS COCOA KRISP  15 OZ\n 3800001203 KELLOGG'S HONEY SMAC 13.1 O\n 3800001210 KELLOGGS HONEY SMACK 17.6 O\n 3800001211 KELLOGGS HONEY SMACK 17.6 O\n 3800001411    KELLOGGS ALL BRAN 18.3 O\n 3800001500 KELLOGGS SUGAR FROST  10 OZ\n 3800001510 KELLOGG'S FROSTED FL  15 OZ\n 3800001520 KELLOGG'S FROSTED FL  20 OZ\n 3800001527 KELLOGG'S FROSTED FL  25 OZ\n 3800001532 KELLOGG FROSTED FLAK  31 OZ\n 3800001611   KELLOGGS SPECIAL K  12 OZ\n 3800001621   KELLOGGS SPECIAL K  18 OZ\n 3800001630 KELLOGG'S SPEC-K-HAN   5 OZ\n 3800001631 KELLOGG'S SPEC-K-HAN   5 OZ\n 3800001710  KELLOGG FROOT LOOPS  11 OZ\n 3800001711 KELL FROOT LOOPS PP$ 10.9 O\n 3800001720 KELLOGGS FRUIT LOOPS  15 OZ\n 3800001727 KELLOGGS FRUIT LOOPS 19.7 O\n 3800001744  FRUIT LOOPS SHIPPER   1 OZ\n 3800001912  KELLOGGS PRODUCT 19  12 OZ\n 3800002400  KELLOGGS STRAWBERRY 16.5OZ\n 3800002720 KLLGG SGR FRSTD MINI  16 OZ\n 3800002727 KELLOGG FROSTED MINI 20.4 O\n 3800002910 KELLOGG'S APPLE JACK  11 OZ\n 3800002911  KELL APPLE JACKS PP 10.9 O\n 3800002920 KELLOGGS APPLE JACKS  15 OZ\n 3800002970 KELLOGGS APPLE JACKS   19.1\n 3800003301 KELLOGGS FRUITY MRSH  14 OZ\n 3800003500    KELLOGG'S CRISPIX    end\n 3800003510     KELLOGGS CRISPIX 17.9 O\n 3800003530    KELLOGG'S CRISPIX  12 OZ\n 3800003700 KELLOGS RAISIN SQUAR 16.5OZ\n 3800003771 KELL RAISIN SQUARE S   1 OZ\n 3800003801 KELLOGGS FRUITFUL BR  15 OZ\n 3800003802 KELLOGGS FRUITFUL BR  15 OZ\n 3800003900 KELLOGGS APPLE RAISI  13 OZ\n 3800004001 KELLOGGS ALL BRAN EX 11.4 O\n 3800004100 KELLOGGS JUST RT FRT  20 OZ\n 3800004110 KELLOGGS JUST RT FRT 14.1 O\n 3800004120 KELLOGGS JUST RT FRT  20 OZ\n 3800004170 KELLOGGS JUST RT FRT  20 OZ\n 3800004210  KELLOGGS JUST RIGHT  11 OZ\n 3800004220 KLG JST RT FIBER NGT 15.7 O\n 3800004270 KLG JST RT FIBER NGT 15.7 O\n 3800004510 KELLOGG'S CRACKLIN O  14 OZ\n 3800004511 ~KELLOGGS CRACKLIN O  20 OZ\n 3800004530 KELLOGGS CRACKLIN OA  17 OZ\n 3800004900 BITE SIZE FRSTD MINI  19 OZ\n 3800004920 KELL FROST MINI WHTS  24 OZ\n 3800004972 KELLOGGS MINI WHEATS  1.2OZ\n 3800005220   KELLOGG'S  FUN PAK 8.56 O\n 3800005231    KELLOGG'S FUN PAK 6.4 OZ\n 3800005332 KELLOGGS VARIETY PAC 10.5OZ\n 3800008000 KELLOGGS MUESLIX FIV 14.1 O\n 3800008020 MUESLIX RSN ALM CRNC 15.3 O\n 3800008100     KEL MUSELIX BRAN 13.1 O\n 3800008200 KEL MUSELIX GOLDEN C 15.9OZ\n 3800008220 MUSELIX APPL ALM CRN 15.9 O\n 3800008600  KELLOGGS SW GRAHAMS 15.8 O\n 3800008700 S.W. GRAHAM BRWN SGR  17 OZ\n 3800008800 KELLOGGS BLUEBERRY S 16.5OZ\n 3800010400 KELLOGGS NUTRI GRAIN  12 OZ\n 3800010401 KELLOGGS NUTRI GRAIN 12.2 O\n 3800010500 KELLOGGS WHT-RSN NUT 17.4 Z\n 3800010600 NUTRI GRAIN ALMOND R 17.2 O\n 3800010601  ~NUTRI GRAIN ALMOND 17.2 O\n 3800010800  KELLOGGS NUTRIGRAIN 12.1 O\n 3800010900 NUTRI GRAN RAISIN BR  11 OZ\n 3800010901 KELLOGG'S NUTRI-GRAI  13 OZ\n 3800012100     KELL COMMONSENSE 14.8 O\n 3800012121 KELL COMMONSENSE FLA 14.8 O\n 3800012200 COMMONSENSE W/RAISIN 20.5 O\n 3800012221 COMMONSENSE W/RAISIN 18.8 O\n 3800012300         KELL BIG MIX 17.8 O\n 3800012400 KELL BIG MIX W/RAISI  20 OZ\n 3800012500 KELL NUT & HONY CRUN 15.5 O\n 3800012600 KEL OATBAKE RAISIN N 14.7OZ\n 3800012700 KEL OATBAKE HONEY BR 14.7OZ\n 3800012800 KELLOGGS HEARTWISE C 10.3OZ\n 3800012900 KELLOGGS HEARTWISE W  14 OZ\n 3800013010  KELLOGG KENMEI RICE  17 OZ\n 3800013110 KELLOOG KENMEI ALM-R  22 OZ\n 3800013400  ~KELLOGGS CINN MINI 15.1 O\n 3800013510  KELLOGGS DOUBLE DIP 12.1 O\n 3800013520  KELLOGGS DOUBLE DIP 14.8 O\n 3800013540 KELLOGG DOUBLE DIP S   1 OZ\n 3800013544 KELLOGG DOUBLE DIP S   1 OZ\n 3800013600 ~KELLOGG FROSTED BRA 18.9 O\n 3800013610 KELLOGG FROSTED BRAN 18.9 O\n 3800013644  KEL FRST BRAN TRIAL 1.5 OZ\n 3800013700 ~KELLOGG LOWFAT GRAN  14 OZ\n 3800013710 KELLOGGS LOWFAT GRAN 20.5 O\n 3800013730 KELLOGG'S LOW FAT GR 18.5 O\n 3800013800 KELLOGG'S L/F GRANOL  14 OZ\n 3800013830 KLLG LWFT GRANOLA W/  18 OZ\n 3800013900 KELLOGGS RICE KRISPI   14.8\n 3800013930 KEL RICE KRISPIES TR  20 OZ\n 3800014400 ~KELL APPLE CIN RICE 16.2 O\n 3800014500  KELL HC MULTI-GRAIN 16.5OZ\n 3800014600  KELL HC MULTI-GRAIN 11.5 O\n 3800014700 KELL HC RAISN, OAT C 12.3 O\n 3800014910 KEL POP TART BS/CINN 11.1 O\n 3800016310 KEL POP TART FRST ST 12.5OZ\n 3800016400 ~KEL TEMPTATION FR V 11.9 O\n 3800016500 ~KEL TEMP HNY RSTD P 12.3 O\n 3800016820 KLLG HNY CRUNCH CORN 15.1 O\n 3800016830 KLLG HNY CRUNCH CORN 21.3 O\n 3800019010  KELLOGG COCOA FRSTD 16.1 O\n 3800032100 KELLOGGS POP TARTS S  11 OZ\n 3800050530 KELLOGGS RICE KRISPI  15 OZ\n 3800054268 KELLOGG JUMBO ASSORT  25 CT\n 3800054275 KELLOGGS CORN FLAKES  48 OZ\n 3800054276 KELL RICE CRISPIES $  38 OZ\n 3800054279 KELLOGGS RAISIN BRAN  51 OZ\n 3800054280  KELLOGS FRSTED FLKS  50 OZ\n 3800070533  KELLOGG'S VALENTINE  19 OZ\n 3800090120 KELLOGG'S CORN FLAKE  32 OZ\n 3800090530 KELLOGGS RICE KRISPI 13.5OZ\n 3800091527 KELLOGGS BRTHDY CONF  25 OZ\n 3828125001        DOM OAT HONEY  16 OZ\n 3828125005   DOM OAT HON RAISIN  16 OZ\n 3828125029   DOM FROSTED FLAKES  20 OZ\n 3828125030   ~DOM BONUS PACK FR 25.5 O\n 3828125031    HH FROSTED FLAKES  20 OZ\n 3828125033      DOM RAISIN BRAN 25.5 O\n 3828125035       HH RAISIN BRAN 25.5 O\n 3828125037        DOM TASTEEO'S  15 OZ\n 3828125041      DOM FRUIT RINGS  15 OZ\n 3828125045      DOM CRISPY RICE  13 OZ\n 3828125049      DOM CORN FLAKES  18 OZ\n 3828125051       HH CORN FLAKES  18 OZ\n 3828125053 DOMINICK'S T-SIZE SH   ASST\n 3828125057 DOMINICK'S T-SIZE SH   ASST\n 3828125061 DOM APPLE CINNAMON T  15 OZ\n 3828125065 DOM HONEY NUT TASTEE  14 OZ\n 3828125069 DOM MAGIC STARS CERE  14 OZ\n 3828125101  DOM LOW FAT GRANOLA  14 OZ\n 3828125109    DOM APPLE DAPPLES  15 OZ\n 3828125113     DOM CRISP CRUNCH  16 OZ\n 3828125117 DOM CRISPY CORN & RI 12.3 O\n 3828125121  DOM COCOA CRUNCHIES 13.7 O\n 3828125125 DOM FROSTED TASTEEO'  14 OZ\n 3828198033 DOM FRUITY HO-HO-HO'  15 OZ\n 3828198101 DOM TRIAL SIZE CEREA 144 CT\n 3828198105 DOM TRIAL SIZE CEREA 144 CT\n 4117314002        DOM OAT HONEY  16 OZ\n 4165345678     UNCLE SAM CEREAL  10 OZ\n 4240090520  MALT O MEAL CRISP N  40 OZ\n 4240090620 MALT O MEAL CORN FLA  40 OZ\n 4240091020 MALT O MEAL SUG FROS  40 OZ\n 4240091320 MALT O MEAL TOOTIE F  40 OZ\n 4300000000 COCOA PEBBLES ON BOX  17 OZ\n 4300010200 POST BLUEBERRY MORNI 13.5OZ\n 4300010210 POST BLUEBERRY MORNI  15 OZ\n 4300010300 POST GOLDEN RAISIN C 15.5 O\n 4300010305 POST CRANBERRY ALMON  13 OZ\n 4300010370    POST WAFFLE CRISP 13.75O\n 4300010442 POST FRUIT & FIBRE P  15 OZ\n 4300010446 POST FRT&FIBRE DATE/  15 OZ\n 4300010450 POST FRUIT&FIBER DAT  14 OZ\n 4300010510      POST GRAPE NUTS  16 OZ\n 4300010521 POST GRAPE-NUTS CERE  24 OZ\n 4300010526 POST GRAPE NUTS BONU  32 OZ\n 4300010713       ~POST TOASTIES  18 OZ\n 4300010910 POST GRAPE NUT FLAKE  18 OZ\n 4300010934 POST GRAPENUT FLAKES  14 OZ\n 4300011140 POST HONEYCOMB 10 OZ  10 OZ\n 4300011170      POST HONEY COMB  14 OZ\n 4300011171      POST HONEY COMB 14.5 O\n 4300011230 HONEY BUNCHES OATS R  16 OZ\n 4300011240 HONEY BUNCHES OATS-A  16 OZ\n 4300011250 POST OAK FLAKES BONU  15 OZ\n 4300011260      POST OAT FLAKES  12 OZ\n 4300011313 POST/NATURAL BRAN FL  16 OZ\n 4300011410     POST RAISIN BRAN  15 OZ\n 4300011460     POST RAISIN BRAN  20 OZ\n 4300011470  POST NATURAL RAISIN  25 OZ\n 4300011650 POST BANANA NUT CRUN 15.5 O\n 4300011653 ~POST BAN NUT CRUNCH 20.5 O\n 4300011760     POST SUGAR CRISP  18 OZ\n 4300011780 $POST GOLDEN CRISP 1  11 OZ\n 4300011817      POST ALPHA BITS  15 OZ\n 4300011862 POST MARSHMALLO ALPH  14 OZ\n 4300012550 POST BRAN'NOLA CEREA  16 OZ\n 4300012560 ~PST BRN'NOLA W/RSNS  16 OZ\n 4300012600 POST GREAT GRAINS DB  16 OZ\n 4300012601 POST GRT GRAINS CRUN  16 OZ\n 4300012610 POST GRT GRNS RSN DA  16 OZ\n 4300012611 POST GRT GRAINS RAIS  16 OZ\n 4300012950   POST COCOA PEBBLES  11 OZ\n 4300012951   POST COCOA PEBBLES  13 OZ\n 4300012965 COCOA PEBBLES ON BOX  17 OZ\n 4300012970  POST FRUITY PEBBLES  11 OZ\n 4300012971  POST FRUITY PEBBLES  13 OZ\n 4300012974 FRUITY PEBBLES ON BO  17 OZ\n 4300012990    POST DINO PEBBLES 12.5OZ\n 4300018005 NABISCO SHREDDED WHE  15 OZ\n 4300018032   ~NABISCO 100% BRAN  17 OZ\n 4300018050 POST SPOON SIZE SHRD 23.6 O\n 4300018054 NAB SPOON SIZE SHRED 17.2 O\n 4300018059 NABISCO WHEAT N BRAN  18 OZ\n 4300018155 ~NABISCO FROSTED WHE  15 OZ\n 4300018160 POST FROSTED SHREDDE  19 OZ\n 4300099100 HOLIDAY HOME MAG SHI   1 CT\n 5200034844  POPEYE PUFFED WHEAT   6 OZ\n 5200034847   POPEYE PUFFED RICE   6 OZ\n 5200034916 POPEYE FRUIT CURLS C  14 OZ\n 5200034940  POPEYE SWEET CRUNCH  13 OZ\n 5537050440 LFSTREAM BRY GRANOLA 14.9OZ\n 5537050730 LIFESTREAM FRT & NUT 12.4OZ\n 5537051730 LIFESTREAM FRT & NUT 12.4OZ\n 5571206700 WEETABIX WHL WHT CER   7 OZ\n 7151801022 HODGSON MILLS OAT BR  16 OZ\n 7276201213              FAMILIA  12 OZ\n 7572514080  ~GENERIC QUICK OATS  42 OZ\n 9166910113     SPIDERMAN CEREAL 12.5OZ\n 9166912111     SUNFLAKES CEREAL  15 OZ\n79166910113    ~SPIDERMAN CEREAL 12.5OZ\n79166910359 ~MUESLI W/ CRANBERRI 13.5OZ\n79166910537 ~RASPBERRY ALMOND MU 13.5OZ\n79166910605 ~MUESLI STRAWBERRY P 13.5OZ\n79166913217 $ALMOND DELIGHT CERE  15 OZ\n79166915516   RALSTON/WHEAT CHEX  16 OZ\n79166918102    RALSTON RICE CHEX

In [40]:
products[
    products["DESCRIP"].str.contains(
        "SHIRT|T-SH|T-SIZE|COUPON|PACK|BOWL|SPOON",
        case=False,
        na=False
    )
][["UPC", "DESCRIP", "SIZE"]]

            UPC               DESCRIP    SIZE
0           317  $TONY THE TIGER T-SH    ASST
4    1313000050  NAB SPOON SIZE SHRED  23.45O
5    1313000054  NAB SPOON SIZE SHRED  17.2 O
37   1600064360  BIG G BREAKFAST PACK  7.5 OZ
115  1600069880   SINGLE VARIETY PACK    6 OZ
236  3000043316  QUAKER CLUB PACK CAP  2/20 O
385  3828125030    ~DOM BONUS PACK FR  25.5 O
394  3828125053  DOMINICK'S T-SIZE SH    ASST
395  3828125057  DOMINICK'S T-SIZE SH    ASST
461  4300018050  POST SPOON SIZE SHRD  23.6 O
462  4300018054  NAB SPOON SIZE SHRED  17.2 O

## Final Analysis Sample

The analysis sample excludes observations without positive sales or positive
recorded prices, observations flagged as questionable by the dataset's `OK`
indicator, and UPCs identified from product metadata as non-cereal merchandise.

Extreme prices and quantities are not removed solely based on percentile
thresholds. Unusual observations are retained unless product metadata provides
evidence that they are not relevant cereal products.

In [42]:
non_cereal_upcs = [
    317,          # Tony the Tiger T-shirt
    3828125053,   # Dominick's T-size shirt
    3828125057,   # Dominick's T-size shirt
    4300099100    # Holiday Home magazine shipper
]

analysis = sales[
    (sales["MOVE"] > 0) &
    (sales["UNIT_PRICE"] > 0) &
    (sales["OK"] == 1) &
    (~sales["UPC"].isin(non_cereal_upcs))
].copy()

print("Final analysis observations:", len(analysis))
print("Unique products:", analysis["UPC"].nunique())
print("Unique stores:", analysis["STORE"].nunique())
print("Weeks:", analysis["WEEK"].min(), "to", analysis["WEEK"].max())

Final analysis observations: 4706287
Unique products: 485
Unique stores: 93
Weeks: 1 to 399

In [43]:
analysis[
    ["MOVE", "QTY", "PRICE", "UNIT_PRICE", "REVENUE", "PROFIT"]
].describe()

,MOVE,QTY,PRICE,UNIT_PRICE,REVENUE,PROFIT
count,4.706287e+06,4.706287e+06,4.706287e+06,4.706287e+06,4.706287e+06,4.706287e+06
mean,1.927382e+01,1.000920e+00,3.118032e+00,3.116560e+00,5.566786e+01,1.741191e+01
std,4.375995e+01,3.392664e-02,7.636026e-01,7.637774e-01,9.361291e+01,9.849343e+00
min,1.000000e+00,1.000000e+00,5.000000e-02,5.000000e-02,5.000000e-02,-9.969000e+01
25%,7.000000e+00,1.000000e+00,2.650000e+00,2.650000e+00,2.121000e+01,1.277000e+01
50%,1.300000e+01,1.000000e+00,3.150000e+00,3.150000e+00,3.893000e+01,1.663000e+01
75%,2.100000e+01,1.000000e+00,3.590000e+00,3.590000e+00,6.630000e+01,2.003000e+01
max,1.782400e+04,3.000000e+00,9.710000e+00,9.710000e+00,2.673600e+04,9.999000e+01

In [44]:
print("Missing values:")
print(analysis.isna().sum())

print("\nDuplicate store-UPC-week observations:")
print(
    analysis.duplicated(
        subset=["STORE", "UPC", "WEEK"]
    ).sum()
)

Missing values:
STORE               0
UPC                 0
WEEK                0
MOVE                0
QTY                 0
PRICE               0
SALE          4349284
PROFIT              0
OK                  0
DESCRIP             0
SIZE                0
UNIT_PRICE          0
REVENUE             0
dtype: int64

Duplicate store-UPC-week observations:
0

In [45]:
cereal_clean = sales[
    ~sales["UPC"].isin(non_cereal_upcs)
].copy()

In [46]:
cereal_clean.to_parquet(
    "../data/processed/cereal_clean.parquet",
    index=False
)

analysis.to_parquet(
    "../data/processed/cereal_analysis.parquet",
    index=False
)

print("Files saved successfully.")

Files saved successfully.